// import { shortHandAttr } from './shorthand'
import { Space } from './types'

const PKG_VERSION = 'PKG_VERSION'
export const version = PKG_VERSION

export type Spec = {
  baseFontSize?: string
  space?: Space
}

export type Theme = {
  baseFontSize?: string
  space?: Space
}

/**
 * Generates Designspek theme from specification
 * @param {object: Spec} - Designspek specification object
 * @return {object: Theme} Designspek theme object
 */

export const createTheme = (spec: Spec): Theme => {
  let theme = Object.assign({})
  return theme
}

/**
 * Combines style object with Designspek generated theme
 * @param {object} style - camelCased CSS properties or shorthand equivalents
 * @param {object: Theme} theme - theme generated by createTheme()
 * @param {boolean} ssr - default: false. If true, returns string of raw CSS
 * @return {string} CSS classname or string of raw CSS; CSS class is appended to HTML head.
 */

export const styled = (style: {}, theme: Theme, ssr?: boolean): string => {
  let css = 'className'
  return css
}
